services:
  auth-service:
    build: ./backend/auth_service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwitter_db_users
    depends_on:
      - mongo

  post-service:
    build: ./backend/post_service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwitter_db_posts
    depends_on:
      - mongo
  
  friendship-service:
    build: ./backend/friendship_service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwitter_db_friends
    
  frontend:
    build: ./frontend/jwitter
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - post-service
      - friendship-service
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
