services:
  auth-service:
    build: ./backend/auth_service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwitter_db_users
    depends_on:
      - mongo
  
  auth-tests:
    build:
      context: ./backend/auth_service
      dockerfile: Dockerfile.test
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwitter_db_users_test
    volumes:
      - ./backend/auth_service:/app
    tty: true


  post-service:
    build: ./backend/post_service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwitter_db_posts
    depends_on:
      - mongo
  
  post-tests:
    build:
      context: ./backend/post_service
      dockerfile: Dockerfile.test
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwitter_db_posts_test
    volumes:
      - ./backend/post_service:/app
    tty: true
  
  friendship-service:
    build: ./backend/friendship_service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwitter_db_friends
    depends_on:
      - mongo

  friendship-tests:
    build:
      context: ./backend/friendship_service
      dockerfile: Dockerfile.test
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwitter_db_friends_test
    volumes:
      - ./backend/friendship_service:/app
    tty: true
    
  message-service:
    build: ./backend/message_service
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwitter_db_messages
    depends_on:
      - mongo
  
  comment-service:
    build: ./backend/comment_service
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwitter_db_comments
    depends_on:
      - mongo

  comment-tests:
    build: 
      context: ./backend/comment_service
      dockerfile: Dockerfile.test
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwitter_db_comments_test
    volumes:
      - ./backend/comment_service:/app
    tty: true
  
  aireporting-service:
    build: ./backend/aireporting_service
    ports:
      - "8000:8000"
  
  email-service:
    build: ./backend/email_service
    ports:
      - "5005:5005"

  email-tests:
    build:
      context: ./backend/email_service
      dockerfile: Dockerfile.test
    tty: true
      
  frontend:
    build: ./frontend/jwitter
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - post-service
      - friendship-service
      - message-service
      - comment-service
      - aireporting-service

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
